# Generated by Django 4.2.24 on 2025-11-12 02:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descuento_porcentaje', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('vigente_desde', models.DateTimeField()),
                ('vigente_hasta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='Casa', max_length=80)),
                ('linea1', models.CharField(max_length=160)),
                ('linea2', models.CharField(blank=True, max_length=160)),
                ('ciudad', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(default='Chile', max_length=60)),
                ('es_principal', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-es_principal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('innovador', 'Innovador')], default='cliente', max_length=20)),
                ('nombre_mostrar', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('creditos_circulares', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('sistema', 'Seguir sistema')], default='claro', max_length=10)),
                ('color_acento', models.CharField(default='#111111', max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('consentimiento', models.BooleanField(default=False)),
                ('rating_sustentabilidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_calidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zara.campaniaencuesta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('precio__gte', 0)), name='precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='stock_no_negativo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='zara.carrito'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='zara.carrito'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zara.producto'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zara.cupon'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('campania'), name='unica_respuesta_por_email_y_campania'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.CheckConstraint(check=models.Q(('rating_sustentabilidad__gte', 1), ('rating_sustentabilidad__lte', 5)), name='rating_sustentabilidad_1_5'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.CheckConstraint(check=models.Q(('rating_calidad__gte', 1), ('rating_calidad__lte', 5)), name='rating_calidad_1_5'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['rol'], name='zara_perfil_rol_b81d09_idx'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['nivel'], name='zara_perfil_nivel_2f81ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gte', 1)), name='cantidad_minima_1'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__lte', 10)), name='cantidad_maxima_10'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
