# Generated by Django 4.2.24 on 2025-11-12 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TradeInCanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('impacto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('puntos_obtenidos', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes_tradein', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
